version: "3.9"

services:
  gstu-bot:
    image: gstu-bot
    container_name: gstu-bot
    restart: always
    env_file:
      - app/.env
    volumes:
      - ./bot.log:/app/bot.log
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://gstu:gstu@postgres:5432/gstu_db
      - REDIS_URL=redis://redis:6379/0
    command: bash -c "python app/migrate_to_pg.py && python app/bot.py"

  postgres:
    image: postgres:15
    container_name: gstu-postgres
    restart: always
    environment:
      POSTGRES_USER: gstu
      POSTGRES_PASSWORD: gstu
      POSTGRES_DB: gstu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gstu-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
