version: "3.9"

services:
  gstu-bot:
    image: gstu-bot
    container_name: gstu-bot
    restart: always
    env_file:
      - app/.env
    volumes:
      - ./bot.log:/app/bot.log
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://gstu:gstu@postgres:5432/gstu_db
      - REDIS_URL=redis://redis:6379/0
    command: bash -c "python app/migrate_to_pg.py && python app/bot.py"

  postgres:
    image: postgres:15
    container_name: gstu-postgres
    restart: always
    environment:
      POSTGRES_USER: gstu
      POSTGRES_PASSWORD: gstu
      POSTGRES_DB: gstu_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gstu"]
      interval: 5s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7
    container_name: gstu-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
