version: '3.8'

services:
  gstu-bot:
    build: .
    container_name: gstu-schedule-bot
    restart: always
    env_file:
      - app/.env
    volumes:
      - ./app:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
